### ISSUE TITLE
CSS 属性 justify-content

### ISSUE THREAD

**Issue by drodata** [drodata/learning-notes#4]
```css
.container {
  display: flex;
  flex-direction: column;
  min-height: 100%;
  justify-content: space-between;
  font-size: 32rpx;
  font-family: -apple-system-font,Helvetica Neue,Helvetica,sans-serif;
}
```

<img width="369" alt="screen shot 2017-05-21 at 3 00 19 pm" src="https://cloud.githubusercontent.com/assets/5827655/26281866/7761b2f8-3e36-11e7-884c-045847a6495a.png">

- http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html
